from app.models import db, Image, environment, SCHEMA


def seed_images():
    images = [{"url": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg", "owner_id": 1, "product_id": 1, "review_id": None},
              {"url": "https://media.istockphoto.com/id/503157860/photo/enjoying-the-fresh-air.jpg?s=612x612&w=0&k=20&c=7nYcClKuS-u0hr98OxS3LSBz3Pia_83RZ4XHf0wC1Uo=", "owner_id": 1, "product_id": 1, "review_id": None}, {
                  "url": "https://media.istockphoto.com/id/501570208/photo/enjoying-a-solitary-walk.jpg?s=612x612&w=0&k=20&c=LtEGQmX1AWom4B7N9ruOqRyY7toFG4pLdJDyLizBVLA=", "owner_id": 1, "product_id": 1, "review_id": None},
              {"url": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
               "owner_id": 3, "product_id": 2, "review_id": None},
              {"url": "https://media.istockphoto.com/id/1221635484/vector/mens-white-short-sleeve-t-shirt-design-templates-vector-illustration.jpg?s=612x612&w=0&k=20&c=Yr-4WlsM9RIKDrJws-tPSWnw2QmBsMjbjn3cV8ysksk=",
               "owner_id": 3, "product_id": 2, "review_id": None},
              {"url": "https://media.istockphoto.com/id/907605102/photo/handsome-man.jpg?s=612x612&w=0&k=20&c=yuSrrY2-SfDFT3T4YkDmzqA7Y8Iy1_HxSzagZqmsbp0=",
               "owner_id": 3, "product_id": 2, "review_id": None},
              {"url": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
               "owner_id": 2,	"product_id": 3,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1208588875/photo/portrait-of-man-wearing-smart-casual-clothes-posing-sitting-on-chair.jpg?s=612x612&w=0&k=20&c=V5UjrUJJ_VFwAS5eQfeFdJmd_NXivtSBf_0JyrjfVuY=",
               "owner_id": 2,	"product_id": 3,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/170900420/photo/handsome-business-man.jpg?s=612x612&w=0&k=20&c=gXSmpXclr5IV69n2ImHLsf3_OZtcy46ba1B26TVeqMA=",
               "owner_id": 2,	"product_id": 3,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
               "owner_id": 3,	"product_id": 4,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/946103052/photo/blue-longsleeve-cotton-tshirt-on-a-mannequin-isolated.jpg?s=612x612&w=0&k=20&c=AyrxjKK7ZRl6CDRolLX-LXcVn7I-cg2E_QdMarPTqh4=",
               "owner_id": 3,	"product_id": 4,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1438991153/photo/mens-round-neck-full-sleeves-t-shirt.jpg?s=612x612&w=0&k=20&c=xd0xRiin809ff5WEpHG9FrrHk1BjLJZ_BvgloMPEpB0=",
               "owner_id": 3,	"product_id": 4,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
               "owner_id": 3,	"product_id": 5,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
               "owner_id": 2,	"product_id": 6,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/488548346/photo/gold-rings.jpg?s=612x612&w=0&k=20&c=ZQcQLYF4Eb4ETWAAOEIQdEgY67JsSYg1WbarKIoqblA=",
               "owner_id": 2,	"product_id": 6,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/974377836/photo/3d-illustration-gold-and-silver-engagement-wedding-band-ring-with-curve-out-ornament-and-red.jpg?s=612x612&w=0&k=20&c=vDXPVmXYHNlY3zy42rpXVxMI8cOzV8OHQPd-qC5VR1w=",
               "owner_id": 2,	"product_id": 6,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
               "owner_id": 2,	"product_id": 7,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
               "owner_id": 2,	"product_id": 8,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
               "owner_id": 2,	"product_id": 9,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
               "owner_id": 2,	"product_id": 10,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
               "owner_id": 2,	"product_id": 11,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
               "owner_id": 3,	"product_id": 12,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
               "owner_id": 3,	"product_id": 13,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
               "owner_id": 3,	"product_id": 14,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
               "owner_id": 3,	"product_id": 15,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
               "owner_id": 4,	"product_id": 16,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
               "owner_id": 4,	"product_id": 17,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
               "owner_id": 4,	"product_id": 18,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
               "owner_id": 2,	"product_id": 19,	"review_id": None},
              {"url": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
               "owner_id": 3,	"product_id": 20,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/71w5QLOqkCL._AC_SL1257_.jpg",
               "owner_id": 2,	"product_id": 21,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81Yff31G6oS._SL1500_.jpg",
               "owner_id": 2,	"product_id": 22,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81fDDyMvhkL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 23,	"review_id": None},
              {"url": "https://products3.imgix.drizly.com/ci-sleeman-light-070be94284dbc51a.jpeg?auto=format%2Ccompress&ch=Width%2CDPR&fm=jpg&q=20",
               "owner_id": 3,	"product_id": 24,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81jRbldvVbL._SL1500_.jpg",
               "owner_id": 3,	"product_id": 25,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/818Q+9mjDUL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 26,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81yr9g90dqL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 27,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/71Nu7MkUEOL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 28,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81rff0UVJBL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 29,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81lm8f9Y5tL._AC_SL1500_.jpg",
               "owner_id": 3,	"product_id": 30,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/61HV4bi3EFL._AC_SL1500_.jpg",
               "owner_id": 2,	"product_id": 31,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/71Psf+JrdQL._AC_SL1500_.jpg",
               "owner_id": 2,	"product_id": 32,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81t7Rarmt3L._SL1500_.jpg",
               "owner_id": 2,	"product_id": 33,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81yAJk9YdUL._SL1500_.jpg",
               "owner_id": 2,	"product_id": 34,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/71w-UeHBjjS._SL1500_.jpg",
               "owner_id": 2,	"product_id": 35,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81q6yl0jLkL._SL1500_.jpg",
               "owner_id": 2,	"product_id": 36,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/91TtYBEH9hL.jpg",
               "owner_id": 2,	"product_id": 37,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/71psHRXrnqL.jpg",
               "owner_id": 2,	"product_id": 38,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/41T9ornqs5L.jpg",
               "owner_id": 2,	"product_id": 39,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81LXfBoLlCL.jpg",
               "owner_id": 2,	"product_id": 40,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81wgcld4wxL.jpg",
               "owner_id": 4,	"product_id": 41,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81w5zqdYpeL._SL1500_.jpg",
               "owner_id": 4,	"product_id": 42,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/61gHENr6geS._AC_SL1500_.jpg",
               "owner_id": 4,	"product_id": 43,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/81Pqvqfo8CL._SL1500_.jpg",
               "owner_id": 4,	"product_id": 44,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/61-dqBMLoYL.jpg",
               "owner_id": 4,	"product_id": 45,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/61PJA8Nt8LL._AC_SL1500_.jpg",
               "owner_id": 4,	"product_id": 46,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1263932003/photo/first-aid-kit-with-all-essential-elements.jpg?s=612x612&w=0&k=20&c=NMPRrqUARif44hUM4LuYxDriE6TSI_2LQ-9XEsBcU2I=",
               "owner_id": 2,	"product_id": 47,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1257680640/photo/first-aid-kit.jpg?s=612x612&w=0&k=20&c=h6W-rqxsBEIm6ijhL6bdVrkvJSXkBdgdjTiQAXROmDc=",
               "owner_id": 2,	"product_id": 47,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1158686941/photo/womens-hand-showing-black-tablet-concept-of-taking-photo-or-selfie.jpg?s=612x612&w=0&k=20&c=K2ScWqf7VNKv7jBwaYlfL6Qr_bbd5rF5B455Cj45e9g=",
               "owner_id": 2,	"product_id": 48,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/169977713/photo/boys-with-a-tablet-computer.jpg?s=612x612&w=0&k=20&c=SfCX3E3Zzrw1tIMYi4xTiVaKAIN_rSKbUi7RsayswGo=",
               "owner_id": 2,	"product_id": 48,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1227383211/photo/african-american-mans-portrait-isolated-on-gradient-studio-background-in-neon-light.jpg?s=612x612&w=0&k=20&c=T-HBlhxDMIU5OCKvWuMlAifK7s0iDZAgnc5JgKvebI4=",
               "owner_id": 2,	"product_id": 48,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1287493813/photo/sony-playstation-5-console-and-games.jpg?s=612x612&w=0&k=20&c=QmaTGa-_q2D8bpwPWuudYNmeNb-5Gv1QKP1ruQUnWEM=",
               "owner_id": 2,	"product_id": 49,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/533460435/photo/ps4-controller.jpg?s=612x612&w=0&k=20&c=tlt3Sm7FQxGBaZSwZB8QqrY0VBsSisCRvIId-Hj1abw=",
               "owner_id": 2,	"product_id": 49,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/523257450/photo/mcz-tokido-kos-julio-in-street-fighter-v-ncr-2016.jpg?s=612x612&w=0&k=20&c=d9CY5pWv0DkkPOCsNqcXH5GFKqePrdYpEOvPiOe415E=",
               "owner_id": 2,	"product_id": 49,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1195556294/photo/digital-winner.jpg?s=612x612&w=0&k=20&c=LkXFww0V8J749lFhNp20S1fv47lzO02C6qHblKXAWEA=",
               "owner_id": 2,	"product_id": 50,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/458095137/photo/play-death-rally-on-apple-ipad2.jpg?s=612x612&w=0&k=20&c=u2R3zeSBSqBd_9dQ2Oxhpn78TARZBBTMtvNr8t4glqk=",
               "owner_id": 2,	"product_id": 50,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1002113928/photo/family-using-technology-at-home.jpg?s=612x612&w=0&k=20&c=PZ2YnhPmqKkLIH0g_Z-2tptvrNcQo3FetZKPbwgex8s=",
               "owner_id": 2,	"product_id": 50,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/499309872/photo/tepig-pokemon-2011-happy-meal-toy.jpg?s=612x612&w=0&k=20&c=QhlJ9oHTaG8uQtyNBdYRg0HlPvBBScWdORq_TNZWAxE=",
               "owner_id": 2,	"product_id": 51,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/890646638/photo/cosplayer-dressed-as-pokemon-character.jpg?s=612x612&w=0&k=20&c=k62xv_C5gkvjhDZQl1XoFr30dlIkrlTqnBAN9_NPygQ=",
               "owner_id": 2,	"product_id": 51,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/584759832/photo/playing-pokemon-go.jpg?s=612x612&w=0&k=20&c=qEHXdQGzcUddLtui0_anSxZz2HUXAGTF2ScYxVhMfJw=",
               "owner_id": 2,	"product_id": 51,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/873185080/photo/white-headphones-isolated-3d-illustration.jpg?s=612x612&w=0&k=20&c=Fr11EZasBP6UhbpQCbqCBFrqUIotATBH_ddh5jQ_u1g=",
               "owner_id": 1,	"product_id": 52,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/910131604/photo/white-headphones-isolated.jpg?s=612x612&w=0&k=20&c=CzHaj80HRxNNw-z0yago0tk8J_DDphcjBa0MsR7FkQ4=",
               "owner_id": 1,	"product_id": 52,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/159084950/vector/mafia-gang.jpg?s=612x612&w=0&k=20&c=OxUjmtuYJevEspZiAE1vlKdS1g49Lrt5hTta9Lxn9Ds=",
               "owner_id": 3,	"product_id": 53,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/654573204/vector/%C3%B0%C3%B0%C2%B5%C3%B1%C3%B0%C3%B1%C3%B1.jpg?s=612x612&w=0&k=20&c=v8rqwbNiWSRQfwc6pkOQSLy2PSlyP0JeRgH5qXL3s2I=",
               "owner_id": 3,	"product_id": 53,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1198321891/photo/italian-mafia-gangster.jpg?s=612x612&w=0&k=20&c=aeKlR6oVT_NTXISumQJhrj8Ns2172KEkTZ2jL1xbVok=",
               "owner_id": 3,	"product_id": 53,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1170503452/photo/detective-board-with-photos-of-suspected-criminals-crime-scenes-and-evidence-with-red-threads.jpg?s=612x612&w=0&k=20&c=b-UTVIx6b_pA0eZTsMpG0FZwLSYwDHbwtHYVGRJ3ZgE=",
               "owner_id": 3,	"product_id": 53,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1157960943/photo/cyber-sport-fully-concentrated-professional-cybersport-player-playing-important-match.jpg?s=612x612&w=0&k=20&c=T-6zQK2JYfLIRF1GqsYNyjLY974kkQAhDm5ZDe9zvfc=",
               "owner_id": 3,	"product_id": 54,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1257101256/vector/happy-people-jumping-celebrating-victory-flat-cartoon-characters-illustration.jpg?s=612x612&w=0&k=20&c=mjajhkk2Ylq69UaJMIKZRlF27qHuWJMcZPb9LxmUxqs=",
               "owner_id": 3,	"product_id": 55,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1073717646/vector/business-team-professional-workers-happy-partners-group-team-building-office-male-and-female.jpg?s=612x612&w=0&k=20&c=4x3up-wKAJ2-MRqGikys4yyybi3OqR6IUZ1MLtXNpf0=",
               "owner_id": 3,	"product_id": 55,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1316610969/photo/beautiful-blusher-and-luxury-modern-red-and-orange-lipstick.jpg?s=612x612&w=0&k=20&c=Oy_wgUfBQcM3RAtJquAXBQk2ez1shU6Ub3JnvfSX1i0=",
               "owner_id": 2,	"product_id": 56,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1207674159/photo/beauty-and-fashion.jpg?s=612x612&w=0&k=20&c=51aF_3-H8qWvpdjRUKkqFLI7_edS881gaO66D4aYss4=",
               "owner_id": 2,	"product_id": 57,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/174477864/photo/face-cream-with-cap-off.jpg?s=612x612&w=0&k=20&c=gRVGUbue429hXP8cUppZn6Iu8UzKDnSgOCgt3x8-1mQ=",
               "owner_id": 2,	"product_id": 57,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/1300556782/photo/hygienic-lip-balm-isolated-on-white-background-facial-care-beauty-concept.jpg?s=612x612&w=0&k=20&c=s3qRXZ3Jw_a2PAYQDQQM2K84FzZYylWIjQrM5T_vxCw=",
               "owner_id": 4,	"product_id": 58,	"review_id": None},
              {"url": "https://media.istockphoto.com/id/484517492/photo/perfume-bottles.jpg?s=612x612&w=0&k=20&c=wpaigpZvoJu_huly4o9d9v_xSYDZ1Rd79d4Jqc33rmc=",
               "owner_id": 4,	"product_id": 59,	"review_id": None},
              {"url": "https://m.media-amazon.com/images/I/61ST2yRX2VL._SL1500_.jpg",	"owner_id": 3,	"product_id": 60,	"review_id": None}]

    db.session.add_all([Image(**image)for image in images])
    db.session.commit()


def undo_images():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.images RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM images")

    db.session.commit()
